apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-{{ZONE}}
  namespace: demo-app
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: bb
        image: docker.io/buoyantio/bb:v0.0.7
        ports:
        - containerPort: 8080
        args:
          - terminus
          - --h1-server-port
          - "8080"
          - --sleep-in-millis
          - "200"
          - --response-text
          - "Hello from {{ZONE}}"
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 1000m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: ["{{ZONE}}"]